# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Quibli
email: info@dustyroom.com
description: >- # this means to ignore newlines until "baseurl:"
  Quibli is a collection of shaders, effects and scripts whose first task is to help easily create the look of the japanese animation films.
twitter_username: _dstrm
minimal_mistakes_skin: air
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-mermaid

author:
  name   : "Dustyroom"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Tiny studio working on interactive experiences."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://dustyroom.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/_dstrm"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/_dstrm"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://dustyroom-studio.github.io/quibli-doc/"
    

defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      toc: true
      toc_sticky: true
      # classes: wide
      sidebar:
        nav: "docs"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

logo: "/assets/images/quibli_logo_type_1.png"

mermaid:
  src: https://cdnjs.cloudflare.com/ajax/libs/mermaid/7.1.2/mermaid.min.js
