# Site settings
title: Quibli
masthead_title: " " # Disable title on masthead because the graphic logo has the title.
email: info@dustyroom.com
description: >- # this means to ignore newlines until "baseurl:"
  Quibli is a collection of shaders, effects and scripts whose first task is to help easily create the look of the japanese animation films.
twitter_username: _dstrm
minimal_mistakes_skin: air

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-ZLWECDZBX1"

# https://giscus.app/
repository : "dustyroom-studio/quibli-doc"
comments:
  provider: "giscus"
  giscus:
    repo_id              : "MDEwOlJlcG9zaXRvcnkzOTUxOTYxMTM="
    category_name        : "Announcements"
    category_id          : "DIC_kwDOF4420c4CdSI_"
    discussion_term      : "pathname"
    reactions_enabled    : '1'
    theme                : "noborder_light"
    input_position       : "top"

search: true
search_full_content: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-mermaid

author:
  name   : "Dustyroom"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Tiny studio working on interactive experiences."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://dustyroom.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/_dstrm"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/GBAeuWC9qS"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/_dstrm"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/GBAeuWC9qS"

atom_feed:
  hide: true

defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: true
      toc: true
      toc_sticky: true
      # classes: wide
      sidebar:
        nav: "docs"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

logo: "/assets/images/quibli_logo_type_1.png"

mermaid:
  src: https://cdnjs.cloudflare.com/ajax/libs/mermaid/7.1.2/mermaid.min.js
